name = "kgeu-schedule-bot"
main = "backend/worker.js"
compatibility_date = "2026-09-01"

[vars]
KABINET_API = "https://kabinet.kgeu.ru/api"
WEBAPP_URL = "https://garz1te.github.io/kgeu_schedule_bot"

[[d1_databases]]
binding = "DB"
database_name = "kgeu_schedule_db"
database_id = "dc6805fc-8dfe-4278-933c-9c9cb5b56aae"