name = "kgeu-schedule-bot"
main = "worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[vars]
KABINET_API = "https://kabinet.kgeu.ru/api"
WEBAPP_URL = "https://garz1te.github.io/kgeu_schedule_bot"

[[d1_databases]]
binding = "DB"
database_name = "kgeu_schedule_db"
database_id = "b2dac2d5-d025-439b-9159-4493005059f8"

[triggers]
crons = ["*/5 * * * *"]